# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-state-test-cicd"
    dynamodb_table = "terraform-state-lock"
    encrypt        = true
    key            = "test-cicd/..tfstate"
    region         = "us-east-1"
  }
}
